#!/usr/bin/env python3
"""Export generated responses to a LaTeX appendix chapter."""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path


EPOCH_LABELS = {
    "E1": "E1: DialoGPT-medium (\\texttt{microsoft/DialoGPT-medium})",
    "E2": "E2: BlenderBot (\\texttt{facebook/blenderbot-400M-distill})",
    "E3": "E3: Phi-3-mini-Instruct (\\texttt{microsoft/Phi-3-mini-4k-instruct})",
    "E4": "E4: Qwen2.5-3B-Instruct (\\texttt{Qwen/Qwen2.5-3B-Instruct})",
}

# GoEmotions labels → Portuguese (for appendix prose)
EMOTION_PT = {
    "admiration": "admiração",
    "amusement": "diversão",
    "anger": "raiva",
    "annoyance": "irritação",
    "approval": "aprovação",
    "caring": "cuidado",
    "confusion": "confusão",
    "curiosity": "curiosidade",
    "desire": "desejo",
    "disappointment": "desapontamento",
    "disapproval": "desaprovação",
    "disgust": "nojo",
    "embarrassment": "embaraço",
    "excitement": "excitação",
    "fear": "medo",
    "gratitude": "gratidão",
    "grief": "luto",
    "joy": "alegria",
    "love": "amor",
    "nervousness": "nervosismo",
    "optimism": "optimismo",
    "pride": "orgulho",
    "realization": "realização",
    "relief": "alívio",
    "remorse": "remorso",
    "sadness": "tristeza",
    "surprise": "surpresa",
    "neutral": "neutro",
}


def emotion_label_pt(label: str | None) -> str:
    if not label:
        return "---"
    key = str(label).strip().lower()
    return EMOTION_PT.get(key, key)


def latex_escape(text: str) -> str:
    if not text:
        return "\\textit{[resposta vazia]}"
    repl = {
        "\\": "\\textbackslash{}",
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    out = "".join(repl.get(ch, ch) for ch in text)
    out = out.replace("\n", " ")
    out = re.sub(r"\s+", " ", out).strip()
    return out


def build_tex(rows: list[dict]) -> str:
    by_stim: dict[str, dict] = defaultdict(dict)
    stimuli_order = []
    for r in rows:
        sid = r["stimulus_id"]
        if sid not in by_stim:
            stimuli_order.append(sid)
        by_stim[sid]["text"] = r["input"]
        by_stim[sid][(r["epoch_id"], r["condition"])] = r
        # Emotional context is stimulus-level (same for all epochs/conditions).
        if "emotional_context" not in by_stim[sid] and r.get("emotional_context"):
            by_stim[sid]["emotional_context"] = r["emotional_context"]

    lines = [
        "% Auto-generated by export_appendix_responses.py --- do not edit by hand",
        "\\chapter{Respostas geradas (baseline vs pipeline)}",
        "\\label{AppendixB}",
        "",
        "Este apêndice apresenta as respostas geradas pela pipeline experimental,",
        "organizadas por estímulo. Para cada estímulo indica-se o enunciado de",
        "entrada e o par de emoções dominantes (positiva e negativa) obtido pelo",
        "classificador GoEmotions, o mesmo sinal injectado na condição",
        "\\textit{pipeline}. Seguem-se, por época/modelo, as respostas",
        "\\textit{baseline} (sem sinal) e \\textit{pipeline} (com sinal).",
        "O ficheiro-fonte completo encontra-se em",
        "\\path{appendices/data/all_results.json}.",
        "",
        f"Total de células incluídas: {len(rows)}.",
        "",
    ]

    epochs_present = sorted({r["epoch_id"] for r in rows})
    for sid in stimuli_order:
        block = by_stim[sid]
        lines.append(f"\\section{{Estímulo \\texttt{{{sid}}}}}")
        lines.append(f"\\textit{{{latex_escape(block['text'])}}}")
        lines.append("")
        ctx = block.get("emotional_context") or {}
        pos = emotion_label_pt(ctx.get("dominant_positive_emotion"))
        neg = emotion_label_pt(ctx.get("dominant_negative_emotion"))
        pos_en = latex_escape(str(ctx.get("dominant_positive_emotion") or "---"))
        neg_en = latex_escape(str(ctx.get("dominant_negative_emotion") or "---"))
        lines.append(
            f"Ambivalência (GoEmotions): emoção positiva dominante "
            f"\\textit{{{latex_escape(pos)}}} (\\texttt{{{pos_en}}}); "
            f"emoção negativa dominante "
            f"\\textit{{{latex_escape(neg)}}} (\\texttt{{{neg_en}}})."
        )
        lines.append("")
        for epoch in epochs_present:
            base = block.get((epoch, "baseline"))
            pipe = block.get((epoch, "pipeline"))
            if not base and not pipe:
                continue
            lines.append(f"\\subsection*{{{EPOCH_LABELS.get(epoch, epoch)}}}")
            if base:
                lines.append("\\textbf{Baseline:}")
                lines.append("")
                lines.append(latex_escape(base.get("response", "")))
                lines.append("")
            if pipe:
                lines.append("\\textbf{Pipeline:}")
                lines.append("")
                lines.append(latex_escape(pipe.get("response", "")))
                lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "data" / "all_results.json",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Path to appendixB.tex",
    )
    parser.add_argument(
        "--copy-json",
        type=Path,
        default=None,
        help="Optional archive copy of all_results.json",
    )
    args = parser.parse_args()

    rows = json.loads(args.results.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_tex(rows), encoding="utf-8")
    print(f"Wrote {args.out} ({len(rows)} cells)")
    if args.copy_json:
        args.copy_json.parent.mkdir(parents=True, exist_ok=True)
        args.copy_json.write_text(
            json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(f"Archived JSON to {args.copy_json}")


if __name__ == "__main__":
    main()
